### ISSUE TITLE
Handling Django admin error for extra fields

### ISSUE THREAD

**Issue by An4ik** [best-doctor/flake8-class-attributes-order#14]
Hi, I have used this one for my Django app, it's great tool (thank you) but it always raises a lint error for an extra field defined in Django admin:
```
class MyAdmin(admin.ModelAdmin):
    .....
    
    def is_married(self, obj):
        return obj.maritial_status == 'single
    is_married.short_description = 'Is married
   ....
```

so it's kinda annoying to avoid every extra field (i.g. adding # noqa CCE001)

can we handle it; (Ignore error for **short_description** attr of the subclass admin.ModelAdmin?

thanks

**Comment by Melevir** [comment]
Idea of adding whitelist of class-level attributes assignments doesn't look like a good idea.

I also found the problem in custom django admin fields and solved it with this decorator:

```
def attributed(label=None, **kwargs):
    def decorator(func):
        if label is not None:
            setattr(func, 'label', label)
        for key, value in kwargs.items():
            setattr(func, key, value)
        return func
    return decorator
```

In your case it will be used like that:
```
    @attributed(short_description='Is married')
    def is_married(self, obj):
        return obj.maritial_status == 'single
```

This decorator is allowed to use only for model admin classes. 

Hope this helps!
