### ISSUE TITLE
Automatically sort the functions?

### ISSUE THREAD

**Issue by TylerYep** [best-doctor/flake8-class-attributes-order#20]
**Is your feature request related to a problem? Please describe.**
Similar to the style of isort or black, is it possible to automatically sort the functions?
It seems doable to come up with a script using the results of this extension.

**Describe the solution you'd like**
It could be a separate project or just an additional script to run - just some way for me to stop having to rearrange these by hand!

**Comment by Melevir** [comment]
Thanks for the idea.

Personally, I don't like the idea of autosorting/fixing/styling. I belive, that it does not support creating of habbit of writing correct styled code in the first place. Also I don't think, that this plugin fits the functionality.

But if would like to create the plugin, I would be glad to help by moving validation logic to separate package, that has no connection to flake8 and can be easy intalled, imported and used.

If you think, that the idea is nice and you would like to use it, please, create seperate issue with public API proposition.
