### ISSUE TITLE
attributes order validation

### ISSUE THREAD

**Issue by vchaptsev** [best-doctor/flake8-class-attributes-order#4]
Hi!
As far as I understand, your plugin should be able to deal with it.
Maybe I don't use it properly?

Your validation order: `__init__`, `__str__`, save, delete, `@property`, `@staticmethod`, `@classmethod`, other methods, underscored methods.

My order: `__init__`, `@classmethod`, `@staticmethod`, underscored method, other method, `@property`

```python
class Demo:
    aaa = 1
    bbb = 2

    def __init__(self):
        self.ccc = 3

    @classmethod
    def classm():
        pass

    @staticmethod
    def staticm():
        pass

    def _prim():
        pass

    def defm():
        pass

    @property
    def propm():
        pass
```

Usage:
```bash
➜  python --version        
Python 3.7.3

➜  flake8 --version                         
3.7.8 (flake-mutable: 1.2.0, flake8-blind-except: 0.1.1, flake8-bugbear: 19.3.0, flake8-class-attributes-order: 0.0.3, flake8-comprehensions: 2.1.0, flake8-debugger: 3.1.0, flake8
-eradicate: 0.2.1, flake8-print: 3.1.0, flake8-pytest: 1.3, flake8-string-format: 0.2.3, flake8-variables-names: 0.0.1, flake8_builtins: 1.4.1, flake8_commas: 2.0.0, flake8_isort:
 2.3, flake8_quotes: 2.0.1, logging-format: 0.6.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.3 on Darwin

➜  flake8 demo.py                           

```

**Comment by Melevir** [comment]
Thanks for the report.

You should enable strict mode for that precision. Sadly, strict mode enabling was broken, but now it is fixed.

Please, update to `flake8-class-attributes-order==0.0.5` and run flake8 with `--use-class-attributes-order-strict-mode` (or add `use_class_attributes_order_strict_mode = True` to flake8 config).

That strict mode thing is not documented, I'll fix it soon.
